/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package application.java;

import org.junit.Test;
import org.apache.log4j.Logger;
import static org.junit.Assert.*;


public class TestApp {

	@Test
	public void start() throws Exception {
		EnrollAdmin.main(null);
		RegisterUser.main(null);
		ClientUtilities.InitLedger();
	}
	// Creates asset7, modify the parameters to create other assets
	@Test
	public void CreateAssetTest() throws Exception {
		ClientUtilities.CreateAsset("asset7", "magenta", "20", "kenysha", "800");
	}

	// Reads asset1, modify the parameters to read other assets
	@Test
	public void ReadAssetTest() throws Exception {
		ClientUtilities.ReadAsset("asset7");
	}

	// Updates asset3, modify the parameters to read other assets
	@Test
	public void UpdateAssetTest() throws Exception {
		ClientUtilities.UpdateAsset("asset3", "blue", "20", "Jin Soo", "600");
	}

	// Deletes asset2, modify the parameters to delete other assets
	@Test
	public void DeleteAssetTest() throws Exception {
		ClientUtilities.DeleteAsset("asset2");
	}

	// Transfers asset1 to arturo, modify the parameters to transfer other assets
	@Test
	public void TransferAssetTest() throws Exception {
		ClientUtilities.TransferAsset("asset1", "arturo");
	}
	// Outputs all the assets
	@Test
	public void GetAllAssetsTest() throws Exception {
		ClientUtilities.GetAllAssets();
	}
}
