#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: org1{{PEER_NAME}}-ccaas-{{CHAINCODE_NAME}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: org1{{PEER_NAME}}-ccaas-{{CHAINCODE_NAME}}
  template:
    metadata:
      labels:
        app: org1{{PEER_NAME}}-ccaas-{{CHAINCODE_NAME}}
    spec:
      containers:
        - name: main
          image: {{CHAINCODE_IMAGE}}
          imagePullPolicy: IfNotPresent
          env:
            - name: CHAINCODE_SERVER_ADDRESS
              value: 0.0.0.0:9999
            - name: CHAINCODE_ID
              value: {{CHAINCODE_ID}}
            - name: CORE_CHAINCODE_ID_NAME
              value: {{CHAINCODE_ID}}
          ports:
            - containerPort: 9999

---
apiVersion: v1
kind: Service
metadata:
  name: org1{{PEER_NAME}}-ccaas-{{CHAINCODE_NAME}}
spec:
  ports:
    - name: chaincode
      port: 9999
      protocol: TCP
  selector:
    app: org1{{PEER_NAME}}-ccaas-{{CHAINCODE_NAME}}