#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: org0-tls-ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: org0-tls-ca
  template:
    metadata:
      labels:
        app: org0-tls-ca
    spec:
      containers:
        - name: main
          image: {{FABRIC_CONTAINER_REGISTRY}}/fabric-ca:{{FABRIC_CA_VERSION}}
          imagePullPolicy: IfNotPresent
          env:
            - name: FABRIC_CA_SERVER_CA_NAME
              value: "org0-tls-ca"
            - name: FABRIC_CA_SERVER_DEBUG
              value: "false"
            - name: FABRIC_CA_SERVER_HOME
              value: "/var/hyperledger/fabric-tls-ca-server"
            - name: FABRIC_CA_CLIENT_HOME
              value: "/var/hyperledger/fabric-ca-client"
          ports:
            - containerPort: 443
          volumeMounts:
            - name: fabric-volume
              mountPath: /var/hyperledger
            - name: fabric-config
              mountPath: /var/hyperledger/fabric-tls-ca-server/fabric-ca-server-config.yaml
              subPath: fabric-tls-ca-server-config.yaml
          readinessProbe:
            tcpSocket:
              port: 443
            initialDelaySeconds: 2
            periodSeconds: 5
      volumes:
        - name: fabric-volume
          persistentVolumeClaim:
            claimName: fabric-org0
        - name: fabric-config
          configMap:
            name: org0-config

---
apiVersion: v1
kind: Service
metadata:
  name: org0-tls-ca
spec:
  ports:
    - name: tls
      port: 443
      protocol: TCP
  selector:
    app: org0-tls-ca