# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.7'

services:
  peer0.org1.example.com:
    volumes:
      - ./podman/peercfg:/etc/hyperledger/peercfg

  peer0.org2.example.com:
    volumes:
      - ./podman/peercfg:/etc/hyperledger/peercfg

  cli:
    volumes:
      - ./podman/peercfg:/etc/hyperledger/peercfg
